const List<String> commonItems = [
  "motor",
  "gyújtáskábelek",
  "gyújtógyertyák",
  "gyújtótrafó",
  "vízhűtő rendszer",
  "fékdob",
  "féktárcsa",
  "fékolaj",
  "olajszűrő",
  "kipufogórendszer",
  "katalizátor",
  "porlasztó",
  "kuplung",
  "sebességváltó",
  "klíma",
  "fényszóró",
  "akkumulátor",
  "karosszéria",
  "belső világítás",
  "lökhárító",
];
